version: '3.1'
services:
  api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_RUN_PORT=8050: "4000"
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres
    networks:
      - webnet

networks:
  webnet:
